# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/cmake/bin/cmake

# The command to remove a file.
RM = /opt/cmake/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspaces/Lab/Projects/project-9-final-project-bread-on-the-pan

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspaces/Lab/Projects/project-9-final-project-bread-on-the-pan

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/cmake/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/cmake/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/Lab/Projects/project-9-final-project-bread-on-the-pan/CMakeFiles /workspaces/Lab/Projects/project-9-final-project-bread-on-the-pan//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/Lab/Projects/project-9-final-project-bread-on-the-pan/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

classes/Drawable.o: classes/Drawable.cc.o
.PHONY : classes/Drawable.o

# target to build an object file
classes/Drawable.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/classes/Drawable.cc.o
.PHONY : classes/Drawable.cc.o

classes/Drawable.i: classes/Drawable.cc.i
.PHONY : classes/Drawable.i

# target to preprocess a source file
classes/Drawable.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/classes/Drawable.cc.i
.PHONY : classes/Drawable.cc.i

classes/Drawable.s: classes/Drawable.cc.s
.PHONY : classes/Drawable.s

# target to generate assembly for a file
classes/Drawable.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/classes/Drawable.cc.s
.PHONY : classes/Drawable.cc.s

classes/Empty.o: classes/Empty.cc.o
.PHONY : classes/Empty.o

# target to build an object file
classes/Empty.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/classes/Empty.cc.o
.PHONY : classes/Empty.cc.o

classes/Empty.i: classes/Empty.cc.i
.PHONY : classes/Empty.i

# target to preprocess a source file
classes/Empty.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/classes/Empty.cc.i
.PHONY : classes/Empty.cc.i

classes/Empty.s: classes/Empty.cc.s
.PHONY : classes/Empty.s

# target to generate assembly for a file
classes/Empty.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/classes/Empty.cc.s
.PHONY : classes/Empty.cc.s

classes/Game.o: classes/Game.cc.o
.PHONY : classes/Game.o

# target to build an object file
classes/Game.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/classes/Game.cc.o
.PHONY : classes/Game.cc.o

classes/Game.i: classes/Game.cc.i
.PHONY : classes/Game.i

# target to preprocess a source file
classes/Game.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/classes/Game.cc.i
.PHONY : classes/Game.cc.i

classes/Game.s: classes/Game.cc.s
.PHONY : classes/Game.s

# target to generate assembly for a file
classes/Game.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/classes/Game.cc.s
.PHONY : classes/Game.cc.s

classes/Game_Window.o: classes/Game_Window.cc.o
.PHONY : classes/Game_Window.o

# target to build an object file
classes/Game_Window.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/classes/Game_Window.cc.o
.PHONY : classes/Game_Window.cc.o

classes/Game_Window.i: classes/Game_Window.cc.i
.PHONY : classes/Game_Window.i

# target to preprocess a source file
classes/Game_Window.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/classes/Game_Window.cc.i
.PHONY : classes/Game_Window.cc.i

classes/Game_Window.s: classes/Game_Window.cc.s
.PHONY : classes/Game_Window.s

# target to generate assembly for a file
classes/Game_Window.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/classes/Game_Window.cc.s
.PHONY : classes/Game_Window.cc.s

classes/Player_Class.o: classes/Player_Class.cc.o
.PHONY : classes/Player_Class.o

# target to build an object file
classes/Player_Class.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/classes/Player_Class.cc.o
.PHONY : classes/Player_Class.cc.o

classes/Player_Class.i: classes/Player_Class.cc.i
.PHONY : classes/Player_Class.i

# target to preprocess a source file
classes/Player_Class.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/classes/Player_Class.cc.i
.PHONY : classes/Player_Class.cc.i

classes/Player_Class.s: classes/Player_Class.cc.s
.PHONY : classes/Player_Class.s

# target to generate assembly for a file
classes/Player_Class.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/classes/Player_Class.cc.s
.PHONY : classes/Player_Class.cc.s

main.o: main.cc.o
.PHONY : main.o

# target to build an object file
main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cc.o
.PHONY : main.cc.o

main.i: main.cc.i
.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s
.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cc.s
.PHONY : main.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... classes/Drawable.o"
	@echo "... classes/Drawable.i"
	@echo "... classes/Drawable.s"
	@echo "... classes/Empty.o"
	@echo "... classes/Empty.i"
	@echo "... classes/Empty.s"
	@echo "... classes/Game.o"
	@echo "... classes/Game.i"
	@echo "... classes/Game.s"
	@echo "... classes/Game_Window.o"
	@echo "... classes/Game_Window.i"
	@echo "... classes/Game_Window.s"
	@echo "... classes/Player_Class.o"
	@echo "... classes/Player_Class.i"
	@echo "... classes/Player_Class.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

